unit Model.Clientes;

interface

uses
  Spring,
  Spring.Persistence.Mapping.Attributes,
  System.SysUtils;

type

  [Entity]
  [Table('CLIENTES')]
  TCliente = class
  private

    [AutoGenerated]
    [Column('ID_CLIENTE', [cpRequired, cpPrimaryKey])]
    FID_Cliente: Integer;

    [Column('TIPO_PESSOA', [cpRequired])]
    FTipo_Pessoa: Char;

    [Column('NOME_RAZAO', [cpRequired])]
    FNome_Razao: string;

    [Column('NOME_FANTASIA')]
    FNome_Fantasia: string;

    [Column('CPF_CNPJ', [cpRequired])]
    FCpf_Cnpj: string;

    [Column('IE')]
    FIE: string;

    [Column('RG')]
    FRG: string;

    [Column('DATA_NASCIMENTO')]
    FData_Nascimento: TDate;

    [Column('TELEFONE')]
    FTelefone: string;

    [Column('EMAIL')]
    FEmail: string;

    [Column('ENDERECO')]
    FEndereco: string;

    [Column('NUMERO')]
    FNumero: string;

    [Column('COMPLEMENTO')]
    FComplemento: string;

    [Column('BAIRRO')]
    FBairro: string;

    [Column('CEP')]
    FCep: string;

    [Column('MUNICIPIO')]
    FMunicipio: string;

    [Column('UF')]
    FUF: string;

    [Column('CODIGO_MUNICIPIO')]
    FCodigo_Municipio: Integer;

    [Column('PAIS')]
    FPais: string;

    [Column('CODIGO_PAIS')]
    FCodigo_Pais: Integer;

    procedure SetID_Cliente(const Value: Integer);
    procedure SetTipo_Pessoa(const Value: Char);
    procedure SetNome_Razao(const Value: string);
    procedure SetNome_Fantasia(const Value: string);
    procedure SetCPF_CNPJ(const Value: string);
    procedure SetIE(const Value: string);
    procedure SetRG(const Value: string);
    procedure SetData_Nascimento(const Value: TDate);
    procedure SetTelefone(const Value: string);
    procedure SetEmail(const Value: string);
    procedure SetEndereco(const Value: string);
    procedure SetNumero(const Value: string);
    procedure SetComplemento(const Value: string);
    procedure SetBairro(const Value: string);
    procedure SetCEP(const Value: string);
    procedure SetMunicipio(const Value: string);
    procedure SetUF(const Value: string);
    procedure SetCodigo_Municipio(const Value: Integer);
    procedure SetPais(const Value: string);
    procedure SetCodigo_Pais(const Value: Integer);

  public

    property ID_Cliente: Integer read FID_Cliente write SetID_Cliente;
    property Tipo_Pessoa: Char read FTipo_Pessoa write SetTipo_Pessoa;
    property Nome_Razao: string read FNome_Razao write SetNome_Razao;
    property Nome_Fantasia: string read FNome_Fantasia write SetNome_Fantasia;
    property CPF_CNPJ: string read FCpf_Cnpj write SetCPF_CNPJ;
    property IE: string read FIE write SetIE;
    property RG: string read FRG write SetRG;
    property Data_Nascimento: TDate read FData_Nascimento
      write SetData_Nascimento;
    property Telefone: string read FTelefone write SetTelefone;
    property Email: string read FEmail write SetEmail;
    property Endereco: string read FEndereco write SetEndereco;
    property Numero: string read FNumero write SetNumero;
    property Complemento: string read FComplemento write SetComplemento;
    property Bairro: string read FBairro write SetBairro;
    property CEP: string read FCep write SetCEP;
    property Municipio: string read FMunicipio write SetMunicipio;
    property UF: string read FUF write SetUF;
    property Codigo_Municipio: Integer read FCodigo_Municipio
      write SetCodigo_Municipio;
    property Pais: string read FPais write SetPais;
    property Codigo_Pais: Integer read FCodigo_Pais write SetCodigo_Pais;
  end;

implementation

procedure TCliente.SetID_Cliente(const Value: Integer);
begin
  FID_Cliente := Value;
end;

procedure TCliente.SetTipo_Pessoa(const Value: Char);
begin
  FTipo_Pessoa := Value;
end;

procedure TCliente.SetNome_Razao(const Value: string);
begin
  FNome_Razao := Value;
end;

procedure TCliente.SetNome_Fantasia(const Value: string);
begin
  FNome_Fantasia := Value;
end;

procedure TCliente.SetCPF_CNPJ(const Value: string);
begin
  FCpf_Cnpj := Value;
end;

procedure TCliente.SetIE(const Value: string);
begin
  FIE := Value;
end;

procedure TCliente.SetRG(const Value: string);
begin
  FRG := Value;
end;

procedure TCliente.SetData_Nascimento(const Value: TDate);
begin
  FData_Nascimento := Value;
end;

procedure TCliente.SetTelefone(const Value: string);
begin
  FTelefone := Value;
end;

procedure TCliente.SetEmail(const Value: string);
begin
  FEmail := Value;
end;

procedure TCliente.SetEndereco(const Value: string);
begin
  FEndereco := Value;
end;

procedure TCliente.SetNumero(const Value: string);
begin
  FNumero := Value;
end;

procedure TCliente.SetComplemento(const Value: string);
begin
  FComplemento := Value;
end;

procedure TCliente.SetBairro(const Value: string);
begin
  FBairro := Value;
end;

procedure TCliente.SetCEP(const Value: string);
begin
  FCep := Value;
end;

procedure TCliente.SetMunicipio(const Value: string);
begin
  FMunicipio := Value;
end;

procedure TCliente.SetUF(const Value: string);
begin
  FUF := Value;
end;

procedure TCliente.SetCodigo_Municipio(const Value: Integer);
begin
  FCodigo_Municipio := Value;
end;

procedure TCliente.SetPais(const Value: string);
begin
  FPais := Value;
end;

procedure TCliente.SetCodigo_Pais(const Value: Integer);
begin
  FCodigo_Pais := Value;
end;

end.
